print('\nAFTER -> interface')	

require('interface.bluloco').after()
require('interface.bufferline').after()
require('interface.colorizer').after()
require('interface.cursorline').after()
require('interface.git-blame').after()
require('interface.lualine').after()
require('interface.noice').after()
require('interface.nvim-tree').after()
require('interface.surround').after()
require('interface.telescope').after()
require('interface.toggleterm').after()
require('interface.which-key').after()
